modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
issueTrackerURL="http://github.com/oitsjustjose/geolosys/issues"
license="GNU GPLv3"

[[mods]]
modId="geolosys"
version="${version}"
displayName="Geolosys"
displayURL="http://geolosys.oitsjustjose.com/en/latest/"
credits="Contributors on GitHub"
authors="oitsjustjose"
description='''
A highly configurable terrafirmacraft-style ore generation mod which permits users to configure almost everything, add their own entries, and many compatibility integrations for other mods.

Support me on Patreon at https://patreon.com/oitsjustjose
'''
[[dependencies.geolosys]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.geolosys]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
